<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260403114503 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE favoris (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, client_id INT DEFAULT NULL, book_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8933C43219EB6921 ON favoris (client_id)');
        $this->addSql('CREATE INDEX IDX_8933C43216A2B381 ON favoris (book_id)');
        $this->addSql('ALTER TABLE favoris ADD CONSTRAINT FK_8933C43219EB6921 FOREIGN KEY (client_id) REFERENCES "user" (id)');
        $this->addSql('ALTER TABLE favoris ADD CONSTRAINT FK_8933C43216A2B381 FOREIGN KEY (book_id) REFERENCES book (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE favoris DROP CONSTRAINT FK_8933C43219EB6921');
        $this->addSql('ALTER TABLE favoris DROP CONSTRAINT FK_8933C43216A2B381');
        $this->addSql('DROP TABLE favoris');
    }
}
